name: Deploy Production
on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/deploy.yml"

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy_production:
    name: Deploy backend to Fly.io
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://seu-novo-nome-app.fly.dev

    steps:
      - name: Get code
        uses: actions/checkout@v4

      # NOVO PASSO: Validação do Dockerfile
      - name: Build Docker Image (Dry Run)
        run: |
          docker build -t production-check:latest .
        working-directory: ./backend
        # Este passo apenas verifica se o build completa com sucesso localmente no GitHub

      - name: Setup Flyctl
        uses: superfly/setup-flyctl@master

      - name: Deploy to Fly.io
        # O deploy só acontece se o passo acima ("Build Docker Image") passar
        run: flyctl deploy --remote-only --app financial-backend --org personal
        working-directory: ./backend
